### ISSUE TITLE
Push Notifications integration 

### ISSUE THREAD

**Issue by hieutc299** [yellowmessenger/YMChatbot-iOS#4]
Hi YM,

Thanks for creating this amazing chatbot.

I am going to integrate YMChatbot-iOS into my app.
There is one problem that I have to face in order to enable push notification using firebase.
You already mentioned that `Firebase service account key is required to send notifications. You can share the service account key with us.` However, I don't know how to share it with us. Your document doesn't show the way to share. 

Please let me know how to share firebase service account key with you to enable push notification.

**Comment by kaunteya** [comment]
Hi,
Please connect with your delivery manager for this
